### ISSUE TITLE
generateSign

### ISSUE THREAD

**Issue by jokosembung** [odenktools/php-bca#17]
Mas mohon maaf sebelumnya saya copy fungsi generatesign ini hasilnya kok beda ya ketika body ada datanya, saya coba bandingkan dengan hasil https://sandbox.bca.co.id/utilities/signature berbeda.

`public static function generateSign($url, $auth_token, $secret_key, $isoTime, $bodyToHash = [])
    {
        $hash = hash("sha256", "");
        if (is_array($bodyToHash)) {
            ksort($bodyToHash);
            $encoderData = json_encode($bodyToHash, JSON_UNESCAPED_SLASHES);
            $hash = hash("sha256", $encoderData);
        }
        $stringToSign = $url . ":" . $auth_token . ":" . strtolower($hash) . ":" . $isoTime;
        $auth_signature = hash_hmac('sha256', $stringToSign, $secret_key, false);
        return $auth_signature;
    }`

terimakasih

**Comment by uncle9999** [comment]
#3

**Comment by odenktools** [comment]
hai @jokosembung sepertinya ada kesalahan saat input api, secret dan lainnya, karena sampai detik ini pun seluruh project saya menggunakan library ini fine fine saja

**Comment by uncle9999** [comment]
#5

**Comment by uncle9999** [comment]
#7

**Comment by uncle9999** [comment]
#11

**Comment by uncle9999** [comment]
@uncle9999

**Comment by uncle9999** [comment]
@jokosembung

**Comment by jokosembung** [comment]
yes gan sudah bisa ada kesalahan di body space belum saya hilangkan jadi faile pas generate sign nya

thanks

**Comment by uncle9999** [comment]
https://sandbox.transferwise.tech/openbanking/.well-known/openid-configuration

**Comment by uncle9999** [comment]
@uncle123
