### ISSUE TITLE
Format `Key` tidak valid

### ISSUE THREAD

**Issue by mjniuz** [odenktools/php-bca#6]
Halo

Saya mendapatkan error Format `Key` tidak valid, lalu saya coba comment untuk function httpAuth() di bagian ` $this->validateBcaKey($client_id);
        $this->validateBcaKey($client_secret);`
dan proses auth berjalan dengan lancar.

Mungkin untuk function validateBcaKey() tidak bisa benar2 memvalidate key/secret, karena tiap pengguna mempunyai format yg berbeda

contoh untuk akun saya adalah

> 1xx1xx11-111x-1xxx-x1xx-1111x11xx1x1

1 (mewakili numeric) dan x (mewakili alphabet)

**Comment by Prazzetyo** [comment]
Halo,

Sama juga masalahnya sama saya, error : Format Key Tidak Valid

**Comment by Prazzetyo** [comment]
Mohon bantuannya

**Comment by odenktools** [comment]
udah solved pada [merge](https://github.com/odenktools/php-bca/pull/5)

**Comment by wisnuholic** [comment]
maaf mas, saya pakai latafel 5.5 masih format key tidak valid. terima kasih

**Comment by arkgnan** [comment]
aku install dari composer. masih terdapat bug ini. pada validateBcaKey preg_match awal yg tadi nya 7 diganti 8

**Comment by odenktools** [comment]
udah solved
