### ISSUE TITLE
HMAC Mismatch

### ISSUE THREAD

**Issue by ibordesk** [odenktools/php-bca#8]
Assalammualaikum 
Mau tanya gan, setiap saya mau ujicoba get balance selalu dapat response 
 ```
"body": {
        "ErrorCode": "ESB-14-001",
        "ErrorMessage": {
            "Indonesian": "HMAC Tidak Cocok",
            "English": "HMAC Mismatch"
        }
    }
```
ini fungsi yg saya buat. Barangkali ada solusinya, terima kasih sebelumnya
```
public function stress_check_balance()
{
		$data = $this->Bank_model->get_token_bca()->row();
		$bca = new \Bca\BcaHttp($data->corp_id, $data->client_key, $data->client_secret, $data->api_key, $data->api_secret);
		$gettokens = $bca->httpAuth();
		if($gettokens->code=="200"){
			$datatoken=array(
				'time_expire' => date("Y-m-d H:i:s", time() + (int) $gettokens->body->expires_in),
				'access_token' => $gettokens->body->access_token,
				'description'=>$gettokens->raw_body,
				'status'=>1
			); 
			if($this->Bank_model->update_token_bca($datatoken)){
				$arrayAccNumber = array('0201245680', '0063001004');
				$response = $bca->getBalanceInfo($gettokens->body->access_token, $arrayAccNumber);
				return $response;
			}
		}
	}
```

**Comment by odenktools** [comment]
Di sisi kami tidak ada masalah apapun.. mungkin nilai access_token salah, silahkan cek kembali nilai token tersebut

**Comment by xor9xor** [comment]
Wa'alaikumsalam

Error HMAC berhubungan dengan perhitungan SIGNATURE yang belum benar. Cek semua parameters input **($url, $auth_token, $secret_key, $isoTime, $bodyToHash)** apakah sudah benar?
> generateSign($url, $auth_token, $secret_key, $isoTime, $bodyToHash)

Rumusnya seperti ini:
>StringToSign = HTTPMethod+":"+RelativeUrl+":"+AccessToken+":"+Lowercase(HexEncode(SHA-256(RequestBody)))+":"+Timestamp

>Signature = HMAC-SHA256(apiSecret, StringToSign)

Semua **karakter whitespace** pada **RelativeUrl** dan **RequestBody** harus di strip dan trim.

**Comment by zulham724** [comment]
sama, kayanya ada yg salah waktu cek mutasi, eror nya selalu HMAC Tidak Cocok
