### ISSUE TITLE
Corporate Id tidak valid

### ISSUE THREAD

**Issue by gulbers** [odenktools/php-bca#9]
Sore om, saya coba2 API untuk **getBalanceInfo** dan **getAccountStatement** tapi selalu dapet error: 

`
{
"code": 400,
"raw_body": "{\"ErrorCode\":\"ESB-82-002\", \"ErrorMessage\":{\"Indonesian\":\"Corporate Id tidak valid\" , \"English\":\"Invalid CorporateID\"}}",
"body": {
"ErrorCode": "ESB-82-002",
"ErrorMessage": {
"Indonesian": "Corporate Id tidak valid",
"English": "Invalid CorporateID"
}
},
"headers": {.....
}
}
`

Saya login berhasil dan cek kurs **getForexRate** berhasil.
Bisa dibantu om kenapa masalahnya.
Berikut ini adalah code untuk getBalanceInfo:

`        \Bca\BcaHttp::setTimeZone("Asia/Jakarta");

        $corp_id = "corporate id 10 digit";
        $client_key = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
        $client_secret = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
        $apikey = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
        $secret = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";

        $bca = new \Bca\BcaHttp($corp_id, $client_key, $client_secret, $apikey, $secret);
        // Request Login dan dapatkan nilai OAUTH
        $response = $bca->httpAuth();
        $token = null;
        if ($response->code == 200) {
        $token = $response->body->access_token;
        }

        $arrayAccNumber = array(
            '1234567890'
        );
        $response = $bca->getBalanceInfo($token, $arrayAccNumber);
        echo json_encode($response);`

**Comment by odenktools** [comment]
@gulbers  saya sudah mencoba baik baik saja. silahkan dicoba untuk transfer bisa ngga? kalo ga bisa mungkin ada kesalahan di secret/apikey nya

**Comment by odenktools** [comment]
@gulbers 

Please use this value for sandbox:
CorporateID : BCAAPI2016 
AccountNumber : 0201245680 or 0063001004

https://developer.bca.co.id/documentation/#business-banking

saya menggunakan data diatas tidak terjadi masalah apapun

**Comment by gulbers** [comment]
sorry baru bales, ternyata corporate id nya yang salah.
thanks..

**Comment by odenktools** [comment]
tolong di close yah issue nya
